from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1101, 680)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.CameraPlayer = QtWidgets.QLabel(self.centralwidget)
        self.CameraPlayer.setGeometry(QtCore.QRect(20, 20, 640, 480))
        self.CameraPlayer.setText("")
        self.CameraPlayer.setScaledContents(True)
        self.CameraPlayer.setObjectName("CameraPlayer")
        self.Alert_Text_Correct = QtWidgets.QLabel(self.centralwidget)
        self.Alert_Text_Correct.setGeometry(QtCore.QRect(680, 20, 400, 60))
        self.Alert_Text_Danger = QtWidgets.QLabel(self.centralwidget)
        self.Alert_Text_Danger.setGeometry(QtCore.QRect(680, 20, 400, 60))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.Alert_Text_Correct.setFont(font)
        self.Alert_Text_Correct.setStyleSheet("color: green")
        self.Alert_Text_Correct.setTextFormat(QtCore.Qt.AutoText)
        self.Alert_Text_Correct.setAlignment(QtCore.Qt.AlignCenter)
        self.Alert_Text_Correct.setObjectName("Alert_Text_Correct")
        self.Alert_Text_Danger.setFont(font)
        self.Alert_Text_Danger.setStyleSheet("color: red")
        self.Alert_Text_Danger.setTextFormat(QtCore.Qt.AutoText)
        self.Alert_Text_Danger.setAlignment(QtCore.Qt.AlignCenter)
        self.Alert_Text_Danger.setObjectName("Alert_Text_Danger")
        self.videoStart_Button = QtWidgets.QPushButton(self.centralwidget)
        self.videoStart_Button.setGeometry(QtCore.QRect(680, 100, 400, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.videoStart_Button.setFont(font)
        self.videoStart_Button.setObjectName("videoStart_Button")
        self.detectionStart_Button = QtWidgets.QPushButton(self.centralwidget)
        self.detectionStart_Button.setGeometry(QtCore.QRect(680, 180, 400, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.detectionStart_Button.setFont(font)
        self.detectionStart_Button.setObjectName("detectionStart_Button")
        self.audibleAlert_Button = QtWidgets.QPushButton(self.centralwidget)
        self.audibleAlert_Button.setGeometry(QtCore.QRect(680, 260, 400, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.audibleAlert_Button.setFont(font)
        self.audibleAlert_Button.setObjectName("audibleAlert_Button")
        self.ComuLogo_Image = QtWidgets.QLabel(self.centralwidget)
        self.ComuLogo_Image.setGeometry(QtCore.QRect(720, 340, 300, 300))
        self.ComuLogo_Image.setText("")
        self.ComuLogo_Image.setPixmap(QtGui.QPixmap("Comu.png"))
        self.ComuLogo_Image.setScaledContents(True)
        self.ComuLogo_Image.setObjectName("ComuLogo_Image")
        self.projectName_Text = QtWidgets.QLabel(self.centralwidget)
        self.projectName_Text.setGeometry(QtCore.QRect(20, 520, 640, 121))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.projectName_Text.setFont(font)
        self.projectName_Text.setScaledContents(False)
        self.projectName_Text.setAlignment(QtCore.Qt.AlignCenter)
        self.projectName_Text.setWordWrap(False)
        self.projectName_Text.setObjectName("projectName_Text")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Alert_Text_Correct.setText(_translate("MainWindow", "Her Şey Yolunda"))
        self.Alert_Text_Danger.setText(_translate("MainWindow", "Tehlike Var"))
        self.Alert_Text_Danger.setVisible(False)
        self.videoStart_Button.setText(_translate("MainWindow", "Videoyu Başlat"))
        self.detectionStart_Button.setText(_translate("MainWindow", "Tespit Etmeyi Başlat"))
        self.audibleAlert_Button.setText(_translate("MainWindow", "Sesli Uyarıları Kapat"))
        self.projectName_Text.setText(_translate("MainWindow", "Baret Tanıma Sistemi"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())